authPractice/authpractice/autho/urls.py
from django.urls import path
from autho.views import *

urlpatterns = [
    path('',Home,name='home'),
    path('signup',Sign_Up,name='signup'),
    path('login/',Log_In,name='login'),
    path('logout/',Log_out,name='logout'),
    path('profile/',Profile,name='profile'),
    path('addPost/',AddPost,name='addpost'),
    path('updatePost/<int:id>/',UpdatePost,name='updatepost'),
    path('deletePost/<int:id>/',deletePost,name='deletepost'),
    path('resetpassword/',ResetPassword, name='resetpassword')
]

authPractice/authpractice/authpractice/urls.py
from django.contrib import admin
from django.urls import path,include
import autho
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autho.urls')),
]

authPractice/authpractice/autho/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    desc = models.TextField(max_length=1000)
    
    def __str__(self):
        return f'{self.title}'


authPractice/authpractice/autho/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django import forms
from .models import Post

class SignUp_Form(UserCreationForm):
    email = forms.EmailField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Confirm Password (again)', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'password':forms.PasswordInput(attrs={'class':'form-control'}),
        }
        
class Login_Form(AuthenticationForm):
    email = forms.EmailField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control'}))
    username = UsernameField(label='Username',widget=forms.TextInput(attrs={'autofocus': True ,'class':'form-control'}))
    password = forms.CharField(label='Password', 
                               widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'}))
    class Meta:
        model = User
        fields = ['email']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','desc']
        labels = {'title':'Title', 'desc':'Description'}
        widgets = {'title':forms.TextInput(attrs={'class':'form-control'}),
                    'desc':forms.Textarea(attrs={'class':'form-control'}),
                    }

authPractice/authpractice/autho/views.py
from django.shortcuts import render, redirect,HttpResponseRedirect
from django.contrib.auth.models import Group
from django.contrib.auth import authenticate , login , logout, update_session_auth_hash
from .forms import SignUp_Form, Login_Form, PostForm
from django.contrib import messages
from .models import Post
from django.core.cache import cache
from autho import signals
 

# Create your views here.

def Home(request):
    fm = Post.objects.all()
    return render(request, 'Home.html',{'form':fm})

def Sign_Up(request):
   if request.method == 'POST':
       form = SignUp_Form(request.POST)
       if form.is_valid():
           messages.success(request,'Congratulations {request.user}, You have become a Premium Member of TrackMyWork !! ')
           user = form.save()
           form = SignUp_Form()
    # add user to group
           group = Group.objects.get(name='Author')
           user.groups.add(group)
   else:
       form = SignUp_Form()
   return render(request, 'signup.html',{'form':form}) 

def Log_In(request):
  if not request.user.is_authenticated:
    if request.method == 'POST':
        form = Login_Form(request=request, data=request.POST)
        if form.is_valid():
            uname = form.cleaned_data.get('username') 
            pword = form.cleaned_data.get('password') 
            email = form.cleaned_data.get('email')
            check = authenticate(username=uname,password=pword,email=email)
            if check is not None:
              login(request,check)
              messages.success(request, f'{request.user} Successfully Logged In!')  
              return redirect('/profile/')          
    else:
        form = Login_Form()   
    return render(request, 'login.html',{'form':form})
  else:
    return redirect('/profile/')
 
def Log_out(request):
    logout(request)
    msg = messages.success(request,'Logged Out Successfully !!')
    return render(request, 'Home.html', {'messages':msg})


def ResetPassword(request):
    # if request.user.is_authenticated:
    #     if request.method == 'POST':
    #       fm = PasswordChangeForm(user=request.user, data=request.POST)
    #       if fm.is_valid():
    #         fm.save()
    #         update_session_auth_hash(request,fm.user)
    #         return redirect('/profile/')
    #     else:       
    #       fm = PasswordChangeForm(user=request.user)
    #       return render(request,'resetpassword.html',{'form':fm})
    return redirect('/login/')

def Profile(request):
   if request.user.is_authenticated:
       work = Post.objects.all()
       user = request.user
       fullname = user.get_full_name() #just above user
       gps = user.groups.all() 
       ip = request.session.get('ip')
       ct = cache.get('count',version=user.pk)
       return render(request, 'profile.html', {'form':work,
            'name':request.user,'fullname':fullname, 
            'groups':gps,'ip':ip,'ct':ct})
   else:
       return redirect('/login/')
   
   
def AddPost(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            signals.notification.send(sender=None, request=request,user=['Dipesh','Mate'])
            pf = PostForm(request.POST)
            if pf.is_valid():
              title = pf.cleaned_data.get('title')
              desc = pf.cleaned_data.get('desc')
              ps = Post(title=title, desc=desc)
              ps.save()
              pf = PostForm()
        else:
            pf = PostForm()
        return render(request, 'addPost.html',{'form':pf})
    else:
        return redirect('/login/')
    
    
    
def UpdatePost(request,id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pst = Post.objects.get(pk=id)
            pstfm = PostForm(request.POST, instance=pst)
            if pstfm.is_valid():
               pstfm.save()
        else:
            pst = Post.objects.get(pk=id)
            pstfm = PostForm(instance=pst)
        return render(request, 'updatePost.html',{'form':pstfm})
    else:
        return redirect('/login/')
    
def deletePost(request,id):
    if request.user.is_authenticated:
        if request.method == 'POST':
           fm = Post.objects.get(pk=id)
           fm.delete()
        return HttpResponseRedirect('/profile/')
    else:
        return redirect('/login/')

authPractice/authpractice/autho/templates/Home.html
{% extends 'signup.html' %}

{% block title %} Home Page{% endblock title %}
{% block content %}
{% block navbar %}
{% include 'Navbar.html' %}
{% endblock%}
   <div class="col-sm-10">
    <h3 class="text-success my-5">Home Page</h3>

    {% if request.user.is_authenticated %}
    {% for post in form %}
    <div class="jumbotron jumbotron-fluid jumbo-color">
        <div class="container">
            <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
            <p class="lead" >{{post.desc}}</p>
        </div>
    </div>
    {% endfor %}
    {% else %}
     <p>No Records:</p>
    <a class="btn btn-info" href="{% url 'login' %}">Login</a>  
    {% endif %}

   </div>
{% endblock content %} 

authPractice/authpractice/autho/templates/Navbar.html
{% extends 'signup.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand text-bg-secondary" href="#">Authentication Page</a>
      <div class="navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Signup</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
{% endblock content %}

authPractice/authpractice/autho/templates/addPost.html
{% extends 'signup.html' %}

{% block content %}
    <div class="col-sm-10">
        <h3>Profile/ Add Post</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input class="btn btn-info" type="submit" value="Add">
            <a class="btn btn-danger" href="{% url 'profile' %}">Cancel</a> 

        </form>
    </div>
{% endblock content %}

authPractice/authpractice/autho/templates/login.html
{% extends 'signup.html' %}

{% block title %} Login Page {% endblock title %}

{% block content %}
{% include 'Navbar.html' %}

<h3 class="text-info my-5">Login to Track your Work</h3>
{% for message in messages %} 
<div class="display">
    <p {% if message.tags %} class="alert alert-{{message.tags}} mb-3" {% endif %}>{{message}} </p> 
</div>
{% endfor %}

<form action="" method="POST" novalidate>
    {% csrf_token %}

    {% for fm in form %} <p class="{{fm.as_tag}}" >{{fm.label_tag}} {{fm}} <small class="text text-danger my-3"> {{fm.errors|striptags}} </small> </p> {% endfor form %} 
    <input class="btn btn-info" type="submit" value="Login">
    <a class="btn btn-primary" href="{% url 'signup' %}">SignUp</a>  
    
    {% if form.non_field_errors %} 
      {% for error in form.non_field_errors %} 
        {{error}} 
      {% endfor %} 
    {% endif %}
</form>
{% endblock content %}

authPractice/authpractice/autho/templates/profile.html
{% extends 'signup.html' %}
{% block title %} Profile Page{% endblock title %}

{% block content %}
{% include 'Navbar.html' %}
<h2>User Profile</h2>
<h3>Welcome "{{name}}"</h3>

    {% block msg %}
        {% if messages %} 
                {% for message in messages %} 
                <div class="display">
                    <p {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}} </p>
                    <button type="button" class="close" data-dismiss ="alert" aria-label="Close" >
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
        {% endif %}
    {% endblock msg %}

    {% block leftside %}
        <div class="col-sm-2">
            <h4 class="my-3">{{name}}</h4>
            <h5>{{fullname}}</h5>
            {% for group in groups %} <p>{{group.name}}</p> {% endfor %}
            <h6 class="mt-3">Your IP: {{ip}}</h6>
            <button type="button" class="btn btn-danger">Login Times <span class="badge badge-light">{{ct}}</span></button>
        </div>
    {% endblock leftside %}


    {% block rightside %}
        {% if form %}
            <table class="table">
                <a class=" text-center btn btn-info" href="{% url 'addpost' %}">Add Post</a>
                <thead>
                <tr>
                    <th scope="col" style="width: 2%">id</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col"style="width: 15%">Action</th>
                </tr>
                </thead>
                <tbody>
                    {% for fm in form %} 
                <tr>
                    <th scope="row">{{fm.id}}</th>
                    <td>{{fm.title}}</td>
                    <td>{{fm.desc}}</td>
                    <td class="d-flex g-4 p-3 m-2 text-center">
                        <a class="btn btn-warning px-3 mx-2" href="{% url 'updatepost' fm.id %}">Edit</a> 
                        
                        {% if perms.autho.delete_post %}
                            <form action="{% url 'deletepost' fm.id %}" method="post">
                                {% csrf_token %}
                                <input class="btn btn-danger" type="submit" value="Delete"/>  
                            </form>
                        {% endif %}
                    </td>
                </tr>
                {% endfor form %}
                </tbody>
            </table>
        {% else %}
            <h4 class="text-center alert alert-warning">No Records</h4>
        {% endif %}
    {% endblock rightside %}


{% endblock content %}

authPractice/authpractice/autho/templates/resetpassword.html
{% extends 'signup.html' %}
{% block title %}Reset Password Page{% endblock title %}
{% block content %}
<form action="" method="POST" novalidate>
    {% csrf_token %}

    {% if form.non_field_errors %} 
    {% for error in form.non_field_errors %} 
      {{error}} 
    {% endfor %} 
    {% endif %}

    {% for fm in form %} <p class="{{fm.as_tag}}" >{{fm.label_tag}} {{fm}} {{fm.errors|striptags}}</p> {% endfor form %} 
    <input type="submit" value="Save">
</form>
<a href="{% url 'profile' %}">Profile</a>
<a href="{% url 'signout' %}">Signout</a>
{% endblock content %}

authPractice/authpractice/autho/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">    <title>{% block title %} SignUp Page {% endblock title %}</title>

    <style>
        .success{
            color: greenyellow;
        }
        a{
            color: aquamarine;
        }
    </style>

</head>
<body>
    
    {% block content %}
{% include 'Navbar.html' %}
    <h3 class="text-info my-5">Sign-Up to Become a Premium Member</h3>
    
    {% for message in messages %} 
        <div class="display">
            <p {% if message.tags %} class="alert alert-{{message.tags}} mb-3" {% endif %}>{{message}}</p> 
        </div>
    {% endfor %}
    
    <form action="" method="POST" novalidate>
        {% csrf_token %}
        {% for fm in form %} <p class="{{fm.as_tag}}" >{{fm.label_tag}} {{fm}} <small class="text-danger">  {{fm.errors|striptags}} </small> </p> {% endfor form %} 
        <input class="btn btn-primary" type="submit" value="Sign up">
        
        <a class="btn btn-info" href="{% url 'login' %}">Login</a>  
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %} <small class="alert alert-danger my-2">{{error}}</small> {% endfor %}
        {% endif %}
    </form>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block msg %}
                {% endblock msg %}
            </div>
        </div>

        <div class="row">
            {% block leftside %}

            {% endblock leftside %}

            {% block rightside %}

            {% endblock rightside %}
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% endblock content %}

</body>
</html>

authPractice/authpractice/autho/templates/updatePost.html
{% extends 'signup.html' %}
{% block title %} UpdatePost Page{% endblock title %}
{% block content %}
    <div class="col-sm-10">
        <h3>Profile/ Update Post</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input class="btn btn-info" type="submit" value="Update Post">
            <a class="btn btn-danger" href="{% url 'profile' %}">Cancel</a> 

        </form>
    </div>
{% endblock content %}